services:
  fastapi-microservice:
    build:
      context: ./test-fastapi-microservice
      dockerfile: Dockerfile
    container_name: test-fastapi-microservice
    ports:
      - "8101:8101"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - microservices-network
    restart: unless-stopped

  django-microservice:
    build:
      context: ./test-django-microservice
      dockerfile: Dockerfile
    container_name: test-django-microservice
    ports:
      - "8100:8100"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge